import { StyleSheet } from 'react-native';
import colors from '../constant/colors';

export const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    tableContainer: {
        alignSelf: 'flex-end',
        width: '93%',
        marginTop: 10,
        borderWidth: 1,
        borderColor: colors.borderStroke,
    },
    tableHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: 10,
        paddingTop: 10
        // backgroundColor: colors.grayBg,
    },
    tableHeaderText: {
        padding: 10,
        // borderWidth: 1,
        borderColor: colors.darkGray,
        // color: colors.black,
        fontWeight: '600',
        textAlign: 'center',
    },
    tableRow: {
        flexDirection: 'row',
        // borderBottomWidth: 1,
        borderColor: colors.darkGray,
        paddingVertical: 15,
        paddingHorizontal: 10,
        backgroundColor: '#fff',
    },
    tableCell: {
        textAlign: 'center',
        color: '#333',
    },
    paymentId: {
        width: 100,
    },
    category: {
        width: 150,
    },
    date: {
        width: 100,
    },
    generatedBy: {
        width: 150, // Adjust width for the "Generated By" column
    },
    description: {
        width: 200, // Adjust width for the "Description" column
    },
    checkbox: {
        marginRight: 10,
    },

    container: {
        flex: 1,
        width: '95%',
        backgroundColor: colors.white,
        alignSelf: 'center',
        // borderWidth: 0.3,
        // borderColor: colors.black,
        borderRadius: 10
    },
    headerContainer: {
        alignSelf: 'center',
        width: '95%',
        padding: 10,
        marginTop: 10
    },
    header: {
        fontSize: 18,
        color: colors.black,
        fontWeight: '700',
    },
    bottomButton: {
        bottom: 0,
        // marginBottom: 10,
        width: '100%',
        position: 'absolute'
    },
    errText: {
        fontFamily: 'Lato',
        fontSize: 12,
        fontWeight: '400',
        color: 'red',
        marginTop: 3,
        paddingLeft: 5,
        width: '90%',
        alignSelf: 'center'
    },
    forgotpasswordContainer: {
        width: '100%',
        padding: 20
    },
    noteText: {
        textAlign: 'center',
        color: colors.black,
        fontSize: 14
    },
    termsText: {
        color: colors.primary,
        fontSize: 14,
        fontWeight: '700'
    },
    rememberMeContainer: {
        width: '90%',
        alignSelf: 'center',
        alignItems: 'flex-end',
        marginTop: 10
    },
    dropdownButtonStyle: {
        width: '90%',
        height: 40,
        backgroundColor: colors.white,
        borderWidth: 0.3,
        borderColor: colors.borderStroke,
        alignSelf: 'center',
        // marginTop: 10,
        borderRadius: 10,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: colors.black,
        width: '90%',
        textAlign: 'left',
        left: 5,
        marginTop: 15,
        marginBottom: 5,
        alignSelf: 'center',
    },
    primarycontainer: {
        borderColor: colors.primary,
        borderWidth: 0.8,
        // backgroundColor: '#3F5C88',
        width: '90%',
        flexDirection: "row",
        alignSelf: 'center',
        height: 45,
        borderRadius: 30,
        marginTop: 20,
        justifyContent: 'center',
        alignItems: 'center',
    },
    primarytxt: {
        color: colors.primary,
        fontSize: 14,
        textAlign: "center",
        fontFamily: 'Poppins-Regular',
    },

});