import { StyleSheet } from 'react-native';
import colors from '../constant/colors';

export const styles = StyleSheet.create({
    mainContainer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
    },
    tableContainer: {
        alignSelf: 'flex-end',
        width: '93%',
        marginTop: 10,
        borderWidth: 1,
        borderColor: colors.borderStroke,
    },
    tableHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingBottom: 10,
        paddingTop: 10
        // backgroundColor: colors.grayBg,
    },
    tableHeaderText: {
        padding: 10,
        // borderWidth: 1,
        borderColor: colors.darkGray,
        // color: colors.black,
        fontWeight: '600',
        textAlign: 'center',
    },
    tableRow: {
        flexDirection: 'row',
        // borderBottomWidth: 1,
        borderColor: colors.darkGray,
        paddingVertical: 15,
        paddingHorizontal: 10,
        backgroundColor: '#fff',
    },
    tableCell: {
        textAlign: 'center',
        color: '#333',
    },
    paymentId: {
        width: 100,
    },
    category: {
        width: 150,
    },
    date: {
        width: 100,
    },
    generatedBy: {
        width: 150, // Adjust width for the "Generated By" column
    },
    description: {
        width: 200, // Adjust width for the "Description" column
    },
    checkbox: {
        marginRight: 10,
    },
});
